---
title: "Activité Rapide 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pen & paper

Suppose you have some ratings (on a 1-5 scale, 5 being the best) of a product $\{1, 1, 3, 3, 3, 3, 5, 5 \}$.

a) Represent those results in a contingency table.

b) Draw a barplot using the previous table.

c) Find the mean of the ratings.

d) Find the median of the ratings.

e) Find the mode of the ratings.


## With R

a) 

Concatenate et structure de x :

```{r contingency table}
x <- c(1, 1, 3, 3, 3, 3, 5, 5)
x
str(x) # structure

table(x)
```

b) Baplot

Base plot

```{r viz base plot}
x_table <- table(x)
plot(x_table)
```

```{r ggplot}
library(dplyr)
library(ggplot2)

xdf <- data.frame(x)
# xdf %>%
#         group_by(x) %>% 
#         summarise(nb = n()) %>% 
#         ggplot(data = ., aes(x = x, y = nb)) +
#         geom_col() +
#         xlab("Rates") + ylab("Frequency") +
#         ggtitle("Frequency of the rates") +
#         theme_light()

ggplot(xdf, aes(x = x)) + 
        geom_bar() +
        xlab("Rates") + ylab("Frequency") +
        ggtitle("Frequency of the rates") +
        theme_light()
```

```{r stats}
mean(x)
median(x)
```

