---
title: "TP1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r lib}
library(tidyverse)
```


## Load data

```{r base R}
scores <- read.csv(file = "../data-raw/tp1_1.csv")
scores
```


```{r load data}
scores <- read_csv(file = "../data-raw/tp1_1.csv")
scores
```

```{r datapasta way}
scores <- data.frame(stringsAsFactors=FALSE,
           I = c("S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10",
                 "S11", "S12", "S13"),
       Score = c(43, 31, 38, 40, 40, 41, 28, 41, 43, 41, 41, 41, 35),
           I = c("S14", "S15", "S16", "S17", "S18", "S19", "S20", "S21", "S22",
                 "S23", "S24", "S25", "S26"),
       Score = c(40, 48, 37, 40, 32, 13, 24, 28, 33, 18, 36, 47, 29),
           I = c("S27", "S28", "S29", "S30", "S31", "S32", "S33", "S34", "S35",
                 "S36", "S37", "S38", "S39"),
       Score = c(38, 33, 44, 44, 49, 24, 18, 49, 41, 25, 27, 43, 11),
           I = c("S40", "S41", "S42", "S43", "S44", "S45", "S46", "S47", "S48",
                 "S49", "S50", "S51", "S52"),
       Score = c(33, 33, 35, 45, 43, 9, 36, 30, 12, 25, 16, 36, 25),
           I = c("S53", "S54", "S55", "S56", "S57", "S58", "S59", "S60", "S61",
                 "S62", "S63", "S64", "S65"),
       Score = c(32, 41, 31, 36, 29, 22, 36, 37, 35, 30, 25, 20, 39),
           I = c("S66", "S67", "S68", "S69", "S70", "S71", "S72", "S73", "S74",
                 "S75", "S76", "S77", "S78"),
       Score = c(37, 39, 36, 10, 26, 23, 27, 26, 20, 24, 37, 45, 43),
           I = c("S79", "S80", "S81", "S82", "S83", "S84", "S85", "S86", "S87",
                 "S88", "S89", "S90", "S91"),
       Score = c(44, 19, 34, 39, 24, 34, 34, 21, 38, 19, 42, 46, 50),
           I = c("S92", "S93", "S94", "S95", "S96", "S97", "S98", "S99",
                 "S100", "S101", "S102", "S103", "S104"),
       Score = c(42, 44, 20, 44, 21, 26, 32, 36, 44, 37, 8, 29, 42),
           I = c("S105", "S106", "S107", "S108", "S109", "S110", "S111",
                 "S112", "S113", NA, NA, NA, NA),
       Score = c(27, 33, 25, 18, 44, 37, 48, 29, 35, NA, NA, NA, NA)
)
scores
```

